###Create new user
POST http://localhost:3000/users/ HTTP/1.1
content-type: application/json

{
    "fname": "Chinonso",
    "lname": "Okafor",
    "email": "chinonso.okafor@example.com",
    "phone": 8034567890,
    "role": "organizer"
}

###Update existing user
PUT http://localhost:3000/users/684169583bd02f1fef2e7437 HTTP/1.1
content-type: application/json

{
    "fname": "Chinonsor",
    "lname": "Okafo",
    "email": "chinonsor.okafo@example.com",
    "phone": 8034567990,
    "role": "organizer"
}

### Get all users
GET http://localhost:3000/users/

###Get user by ID
GET http://localhost:3000/users/68409ca1e94c31448f774c48

###Delete user
DELETE  http://localhost:3000/users/68409ca1e94c31448f774c48 HTTP/1.1
